language: ruby
sudo: false
cache: bundler
rvm:
  - 2.2.4
before_script:
  - psql -c 'create database reread_test;' -U postgres
notifications:
  email: false
  slack:
    secure: wZ1UPEcH/Zf/wSPvpR1q76vpUQvAEGuwR5500ML8C+shW7PedvuSZaiZYAOZxhyD17RXzXYroON0ArEk3NUcKD8supPzYjUWzCeWDIFaYxEb7dOm7tpRBf4GuQ/oy8HGsBi947ZTX3WytGWZU0q0aRu2EirPcoY05vzley/hYTI=
